"""Strict, dependency-free verification for ChatMaker Core release manifests.

The release bootstrap runs before the bundled virtual environment exists, so
this module intentionally uses only Python's standard library.  It implements
the RFC 8032 Ed25519 verification equation and applies stricter decoding rules:
points must be canonical, non-small-order members of the prime-order subgroup.
"""

from __future__ import annotations

import base64
import binascii
import hashlib
import hmac
import json
from typing import Any


DOMAIN_SEPARATOR = b"ChatMaker Core Release Manifest v1\0"
OFFICIAL_KEY_ID = "chatmaker-official-2026-01"
OFFICIAL_PUBLIC_KEY = bytes.fromhex(
    "89b25c42329e5deff966621a115f479883b78fd3db5610f34a5600f4e8fd1da9"
)
OFFICIAL_PUBLIC_KEY_FINGERPRINT = (
    "70570b179cf452abcc7486f76a408a25faee3702433663e99b7418498d725f67"
)

_P = 2**255 - 19
_L = 2**252 + 27742317777372353535851937790883648493
_D = (-121665 * pow(121666, _P - 2, _P)) % _P
_SQRT_M1 = pow(2, (_P - 1) // 4, _P)
_IDENTITY = (0, 1, 1, 0)


class ReleaseSignatureError(ValueError):
    """Raised when release signature material is not strictly valid."""


class _DuplicateKey(ValueError):
    pass


def _reject_constant(value: str) -> None:
    raise ValueError(f"non-finite JSON number: {value}")


def _unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise _DuplicateKey(key)
        result[key] = value
    return result


def _contains_float(value: Any) -> bool:
    if isinstance(value, float):
        return True
    if isinstance(value, list):
        return any(_contains_float(item) for item in value)
    if isinstance(value, dict):
        return any(_contains_float(item) for item in value.values())
    return False


def _canonical_json_document(raw: bytes, *, top_level_keys: set[str] | None = None) -> Any:
    if not isinstance(raw, bytes):
        raise ReleaseSignatureError("release_signature_invalid")
    try:
        value = json.loads(
            raw.decode("utf-8"),
            object_pairs_hook=_unique_object,
            parse_constant=_reject_constant,
        )
        if not isinstance(value, dict) or _contains_float(value):
            raise ValueError("unsupported JSON value")
        if top_level_keys is not None and set(value) != top_level_keys:
            raise ValueError("unexpected JSON fields")
        canonical = (
            json.dumps(
                value,
                sort_keys=True,
                separators=(",", ":"),
                ensure_ascii=True,
                allow_nan=False,
            )
            + "\n"
        ).encode("ascii")
    except (UnicodeDecodeError, json.JSONDecodeError, TypeError, ValueError) as exc:
        raise ReleaseSignatureError("release_signature_invalid") from exc
    if not hmac.compare_digest(raw, canonical):
        raise ReleaseSignatureError("release_signature_invalid")
    return value


def _point_add(
    first: tuple[int, int, int, int], second: tuple[int, int, int, int]
) -> tuple[int, int, int, int]:
    x1, y1, z1, t1 = first
    x2, y2, z2, t2 = second
    a = ((y1 - x1) * (y2 - x2)) % _P
    b = ((y1 + x1) * (y2 + x2)) % _P
    c = (2 * _D * t1 * t2) % _P
    d = (2 * z1 * z2) % _P
    e, f, g, h = b - a, d - c, d + c, b + a
    return (e * f % _P, g * h % _P, f * g % _P, e * h % _P)


def _scalar_multiply(
    scalar: int, point: tuple[int, int, int, int]
) -> tuple[int, int, int, int]:
    result = _IDENTITY
    addend = point
    while scalar:
        if scalar & 1:
            result = _point_add(result, addend)
        addend = _point_add(addend, addend)
        scalar >>= 1
    return result


def _points_equal(
    first: tuple[int, int, int, int], second: tuple[int, int, int, int]
) -> bool:
    return (
        (first[0] * second[2] - second[0] * first[2]) % _P == 0
        and (first[1] * second[2] - second[1] * first[2]) % _P == 0
    )


def _decode_point(encoded: bytes) -> tuple[int, int, int, int] | None:
    if len(encoded) != 32:
        return None
    y = int.from_bytes(encoded, "little") & ((1 << 255) - 1)
    sign = encoded[31] >> 7
    if y >= _P:
        return None
    y_squared = y * y % _P
    denominator = (_D * y_squared + 1) % _P
    if denominator == 0:
        return None
    x_squared = (y_squared - 1) * pow(denominator, _P - 2, _P) % _P
    x = pow(x_squared, (_P + 3) // 8, _P)
    if x * x % _P != x_squared:
        x = x * _SQRT_M1 % _P
    if x * x % _P != x_squared or (x == 0 and sign == 1):
        return None
    if x & 1 != sign:
        x = _P - x
    point = (x, y, 1, x * y % _P)
    # Reject torsion and mixed-order points. Official keys and valid R values
    # are in the prime-order subgroup generated by B.
    if _points_equal(_scalar_multiply(8, point), _IDENTITY):
        return None
    if not _points_equal(_scalar_multiply(_L, point), _IDENTITY):
        return None
    return point


_BASE_Y = 4 * pow(5, _P - 2, _P) % _P
_BASE_ENCODED = (_BASE_Y | ((0 if _BASE_Y == 1 else 0) << 255)).to_bytes(32, "little")


def _base_point() -> tuple[int, int, int, int]:
    # RFC 8032 fixes the base point's x coordinate to the even square root.
    encoded = bytearray(_BASE_ENCODED)
    encoded[31] &= 0x7F
    point = _decode_point(bytes(encoded))
    if point is None:  # pragma: no cover - constant self-check
        raise RuntimeError("invalid Ed25519 base point constant")
    return point


_BASE = _base_point()


def verify_ed25519(public_key: bytes, message: bytes, signature: bytes) -> bool:
    """Return whether *signature* is a strict RFC 8032 Ed25519 signature."""

    if not isinstance(public_key, bytes) or not isinstance(message, bytes) or not isinstance(signature, bytes):
        return False
    if len(public_key) != 32 or len(signature) != 64:
        return False
    encoded_r, encoded_s = signature[:32], signature[32:]
    scalar_s = int.from_bytes(encoded_s, "little")
    if scalar_s >= _L:
        return False
    public_point = _decode_point(public_key)
    point_r = _decode_point(encoded_r)
    if public_point is None or point_r is None:
        return False
    challenge = int.from_bytes(
        hashlib.sha512(encoded_r + public_key + message).digest(), "little"
    ) % _L
    left = _scalar_multiply(scalar_s, _BASE)
    right = _point_add(point_r, _scalar_multiply(challenge, public_point))
    return _points_equal(left, right)


def _canonical_signature(value: Any) -> bytes:
    if not isinstance(value, str) or not value.isascii():
        raise ReleaseSignatureError("release_signature_invalid")
    try:
        decoded = base64.b64decode(value, validate=True)
    except (ValueError, binascii.Error) as exc:
        raise ReleaseSignatureError("release_signature_invalid") from exc
    if len(decoded) != 64 or not hmac.compare_digest(
        base64.b64encode(decoded).decode("ascii"), value
    ):
        raise ReleaseSignatureError("release_signature_invalid")
    return decoded


def verify_release_manifest(manifest_bytes: bytes, detached_signature_bytes: bytes) -> dict[str, str]:
    """Verify one canonical manifest against the embedded official key.

    The detached JSON object must itself be canonical and contain exactly
    ``algorithm``, ``key_id`` and ``signature``.  The Ed25519 message is the
    fixed domain separator followed by the exact canonical manifest bytes.
    """

    _canonical_json_document(manifest_bytes)
    detached = _canonical_json_document(
        detached_signature_bytes,
        top_level_keys={"algorithm", "key_id", "signature"},
    )
    if detached.get("algorithm") != "ed25519" or detached.get("key_id") != OFFICIAL_KEY_ID:
        raise ReleaseSignatureError("release_signature_invalid")
    if len(OFFICIAL_PUBLIC_KEY) != 32 or not hmac.compare_digest(
        hashlib.sha256(OFFICIAL_PUBLIC_KEY).hexdigest(),
        OFFICIAL_PUBLIC_KEY_FINGERPRINT,
    ):
        raise ReleaseSignatureError("release_signature_invalid")
    signature = _canonical_signature(detached.get("signature"))
    if not verify_ed25519(
        OFFICIAL_PUBLIC_KEY,
        DOMAIN_SEPARATOR + manifest_bytes,
        signature,
    ):
        raise ReleaseSignatureError("release_signature_invalid")
    return {
        "algorithm": "ed25519",
        "key_id": OFFICIAL_KEY_ID,
        "fingerprint_sha256": OFFICIAL_PUBLIC_KEY_FINGERPRINT,
    }


__all__ = [
    "DOMAIN_SEPARATOR",
    "OFFICIAL_KEY_ID",
    "OFFICIAL_PUBLIC_KEY",
    "OFFICIAL_PUBLIC_KEY_FINGERPRINT",
    "ReleaseSignatureError",
    "verify_ed25519",
    "verify_release_manifest",
]
